# Today's Agenda:

#### 1. Introduction and Python Basics
#### 2. 3D Plots and Sets for Optimization
#### 3.  SciPy (Linear Programming) and Application (Drones)
#### 4. Graph Theory (NetworkX) and Wrap-up

## Part 1: Introduction and Python Basics

### What is Python and Who cares?

> Python is an interpreted, object-oriented, high-level programming language with dynamic semantics. *[Definition from Python.org](https://www.python.org/doc/essays/blurb/)

It is a widely used tool employed to solve, visualize problems in many fields that include but not limited to:
1. **Mathematics**
2. **Engineering**
3. Economics
4. Medicine
5. All other fields of Science

Many also use it to create software tools, or run web applications.

Relevant to today's presentation, we can use it in the following areas:
1. Optimization
2. Linear Algebra
3. Graph Theory
4. Data Processing and Visualization (of all the above areas)
---

### What is a Jupyter Notebook:

It is an interactive computing environment that enables users to author notebook documents that include:

1. Live code
2. Interactive widgets
3. Plots
4. Narrative text
5. Equations (LaTeX)
6. Images
7. Video  

See Reference for LaTeX: https://towardsdatascience.com/write-markdown-latex-in-the-jupyter-notebook-10985edb91fd

### Python Basics - Data Types and Numpy and Plots

In [1]:
# This is a comment

# This is Addition
1.0 + 2

3.0

In [2]:
# This is a variable
a = 5

# This is how to view/print/output the variable
print(a)

5


In [3]:
# This is a string
print("Hellow World!!")

Hellow World!!


In [4]:
# This is a fancier way to print the variable
print("A is: ", a, a+5)

A is:  5 10


In [5]:
# Or simply

print(a+5)
a

10


5

<img src="files/builtindatatypes.jpg" alt="Drawing" style="width: 600px;"/>

In [6]:
# This is a tuple
b = (3.0,4,5)
print(b)

z,y,x = b
print(z, y, x)

a, b = (1, 2)
print(a, b)
b, a = (a, b)
print(a, b)

(3.0, 4, 5)
3.0 4 5
1 2
2 1


In [7]:
# This is a list
c = [5, 6, 90]
d = ["apple", "hmm", "yup", "hmm"]
print("\nList:\n", c)
print(d)

# This is a set
e = {9, 1, 3, 4, 4, 5}
f = {"qwerty", "hello", "a", "b", "qwerty", 9}
print("\nSet: ")
print(e)
print(f)


List:
 [5, 6, 90]
['apple', 'hmm', 'yup', 'hmm']

Set: 
{1, 3, 4, 5, 9}
{'b', 9, 'hello', 'a', 'qwerty'}


In [8]:
# This is a bool(boolean); TRUE/FALSE
print(3 == 4, "\n")

a = 5
b = 7
print(a < b, "\n")
print(a > b, "\n")
print(a-b >= -2, "\n")


False 

True 

False 

True 



In [9]:
# Lets try doing some math. How to add vectors ??

A = [2, 3, 4, 5]
B = [0, 1, 2, 3]

print(A)
A + B

[2, 3, 4, 5]


[2, 3, 4, 5, 0, 1, 2, 3]

### NumPy
The NumPy library is a popular Python library used for scientific computing applications, and is an acronym for "Numerical Python". NumPy's operations are divided into three main categories: Fourier Transform and Shape Manipulation, Mathematical and Logical Operations, and Linear Algebra and Random Number Generation. To make it as fast as possible, NumPy is written in C and Python. https://numpy.org/

In [10]:
# This is an import statement
import numpy as np

C = np.array([2, 3, 4, 5])
D = np.array([0, 1, 2, 3])

print(C)
C

[2 3 4 5]


array([2, 3, 4, 5])

In [11]:
# so lets add
C+D

array([2, 4, 6, 8])

In [12]:
# Other ops
print(C - D)
print(C * D)
print(D / C)

[2 2 2 2]
[ 0  3  8 15]
[0.         0.33333333 0.5        0.6       ]


In [13]:
# Using numpy functions https://numpy.org/

# Add
E = np.add(C, D)
print(E)

# inverse
F = np.array([[1, 2],[3, 4]])
print("\nF:")
print(F)

np.linalg.inv(F)

[2 4 6 8]

F:
[[1 2]
 [3 4]]


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [14]:
# Array creation (For more functions, see: https://numpy.org/doc/stable/reference/routines.html)

#Identity matrix
I = np.identity(7)
print(I)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


### Plots (Matplotlib)

Matplotlib graphs your data on Figures (i.e., windows, Jupyter widgets, etc.), each of which can contain one or more Axes (i.e., an area where points can be specified in terms of x-y coordinates (or theta-r in a polar plot, or x-y-z in a 3D plot, etc.).  
  
Reference: https://matplotlib.org/tutorials/introductory/usage.html#sphx-glr-tutorials-introductory-usage-py  
Gallery: https://matplotlib.org/gallery/index.html?highlight=gallery

In [15]:
#Array of numbers https://numpy.org/doc/stable/reference/generated/numpy.arange.html#numpy.arange
Nums = np.arange(-50, 51)
print(Nums)

# Y = X^2: Use either numpy.square(X) or X**2
Y = Nums**2
print("\n\nY:")
print(Y)

[-50 -49 -48 -47 -46 -45 -44 -43 -42 -41 -40 -39 -38 -37 -36 -35 -34 -33
 -32 -31 -30 -29 -28 -27 -26 -25 -24 -23 -22 -21 -20 -19 -18 -17 -16 -15
 -14 -13 -12 -11 -10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3
   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21
  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39
  40  41  42  43  44  45  46  47  48  49  50]


Y:
[2500 2401 2304 2209 2116 2025 1936 1849 1764 1681 1600 1521 1444 1369
 1296 1225 1156 1089 1024  961  900  841  784  729  676  625  576  529
  484  441  400  361  324  289  256  225  196  169  144  121  100   81
   64   49   36   25   16    9    4    1    0    1    4    9   16   25
   36   49   64   81  100  121  144  169  196  225  256  289  324  361
  400  441  484  529  576  625  676  729  784  841  900  961 1024 1089
 1156 1225 1296 1369 1444 1521 1600 1681 1764 1849 1936 2025 2116 2209
 2304 2401 2500]


In [16]:
import matplotlib.pyplot as plt #Library for plots

plt.plot(Nums, Y)

### 3D Plots

In [17]:
# Creating a 3D surface plot Z^2 = X^2 + Y^2
X = np.arange(0, 3) # X = [0 1 2]
Y = np.arange(0, 3) # Y = [0 1 2]

# Generate intersections of X, Y: See Output
Grid = np.meshgrid(X, Y)
Grid

[array([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]), array([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]])]

In [18]:
# Lets seperate those arrays
XX, YY = Grid
print(XX)
print()
print(YY)

[[0 1 2]
 [0 1 2]
 [0 1 2]]

[[0 0 0]
 [1 1 1]
 [2 2 2]]


In [19]:
# Compute output ZZ = (XX)^2 + (YY)^2: Use either numpy.square or **
ZZ = XX**2 + YY**2
ZZ

array([[0, 1, 4],
       [1, 2, 5],
       [4, 5, 8]], dtype=int32)

In [20]:
%matplotlib notebook
from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure()
ax = Axes3D(fig)

ax.plot_surface(XX, YY, ZZ)

<IPython.core.display.Javascript object>

In [21]:
# More points

X = np.arange(-10, 10, 0.1) # This is Input

XX, YY = np.meshgrid(X, X)

# ZZ = (XX)^2 + (YY)^2: Use either numpy.square or **
ZZ = XX**2 + YY**2

fig = plt.figure()
ax = Axes3D(fig)

ax.plot_surface(XX, YY, ZZ) # This Gives Output

<IPython.core.display.Javascript object>

### Function  
  

<img src="files/functionImage.jpg" alt="Drawing" style="width: 300px;"/>
<span style="font-family:Comic Sans MS"><center>From Wikipedia</center></span>  

**Function Syntax**
<img src="files/Python-Function-Syntax.png" alt="Drawing" style="width: 500px;"/>
<span style="font-family:Comic Sans MS"><center>From learnbyexample.org</center></span>


In [22]:
# Function Definition in Python
def myAdder(X, Y):
    Z = X + Y    
    return Z

In [23]:
# Calling the function
Sum = myAdder(np.array([2,3,4]), np.array([1,2,3]))
Sum

array([3, 5, 7])

In [24]:
# Function Definition in Python
def myFunPlotsin3D(X, Y):
    
    XX, YY = np.meshgrid(X, Y)

    # ZZ = (XX)^2 + (YY)^2: Use either numpy.square or **
    ZZ = XX**2 + YY**2

    fig = plt.figure()
    ax = Axes3D(fig)

    ax.plot_surface(XX, YY, ZZ) # This Gives Output
    
    return None    

In [25]:
# Calling the Function
A = np.arange(-20, 30)
B = np.arange(-100, 200)

myFunPlotsin3D(A, B)

<IPython.core.display.Javascript object>

<span style="font-family:Comic Sans MS">->>> Examples in HW3_3- -->>></span> [Link for HW3 (Examples)](https://mybinder.org/v2/gh/Sridhar701Pitt/OptimizationPresentationMATH/master?filepath=HW3_Updated.ipynb)

## 2. 3D Plots and SciPy (Linear Programming)

### Ipyvolume

IPyvolume is a Python library to visualize 3d volumes and glyphs (e.g. 3d scatter plots), in the Jupyter notebook, with minimal configuration and effort. In contrast to matplotlib, it also supports widgets.  
Reference: https://ipyvolume.readthedocs.io/en/latest/#  
Examples: https://ipyvolume.readthedocs.io/en/latest/examples.html

In [26]:
import ipyvolume as ipv #Imports a library called ipyvolume to help with plotting

# More points - Now with ipyvolume
X = np.arange(-10, 10, 0.1) # This is Input

XX, YY = np.meshgrid(X, X)

# ZZ = (XX)^2 + (YY)^2: Use either numpy.square or **
ZZ = XX**2 + YY**2

fig = ipv.figure()

ipv.plot_surface(XX, YY, ZZ) # This Gives Output
ipv.show()

#### Sets for Optimization

Lets take 4 points in 3D space:  
P1 = ( 1.0, 1.0, 1.0)  
P2 = ( 2.0,-1.0, 0.0)  
P3 = (-2.0,-1.5, 0.5)  
P4 = (-1.0, 0.0,-0.5)

Heres a Plot:

In [27]:
import ipyvolume as ipv #Imports a library called ipyvolume to help with plotting
import numpy as np #Library import for array creation, and manipulation

# 2D array with 4 rows (P1, P2, P3, P4) and 3 columns (X, Y, Z) coordinates
Points = np.array([[ 1.0, 1.0, 1.0], [ 2.0,-1.0, 0.0], [-2.0,-1.5, 0.5], [-1.0, 0.0,-0.5]])
# Set = np.array([[ 1.0, 1.0, 1.0], [ 0.5, 1.0, 2.0], [ 2.0, 1.5, 0.5], [ 1.0, 2.0, 0.5]]) # All points in 1st quadrant
Points

array([[ 1. ,  1. ,  1. ],
       [ 2. , -1. ,  0. ],
       [-2. , -1.5,  0.5],
       [-1. ,  0. , -0.5]])

In [28]:
XVals, YVals, ZVals = np.transpose(Points)


fig = ipv.figure()
# Plot the points
ipv.scatter(XVals,YVals,ZVals, size=3, marker='sphere')
# Add limits to axes
ipv.xyzlim(-3, 3)

# Plot Axes Planes - Run the function declaration first
plotAxesPlanes()

ipv.show()

NameError: name 'plotAxesPlanes' is not defined

#### Affine, Conical, and Convex Sets

Take the **Linear Combination**: 
$$ \sum_{i=1}^{4} a_{i} P_{i} $$

For **Affine Combination**, we have: $$ \sum_{i=1}^{4} a_{i} = 1 $$

In [ ]:
# Get 1000 random Values for each of a1, a2 and a3 between [-1 to 1)
a1, a2, a3 = (10) * np.random.random_sample((3, 1000)) - 5

# Calculate a4 to satisfy the **affine** condition
a4 = 1.0 - (a1 + a2 + a3)

# Get A, B, C, D values from Points array
P1, P2, P3, P4 = Points

# Multiply to get the Linear combination with the affine constraints
Term1  = np.multiply(a1[:,None],P1[None])
Term2  = np.multiply(a2[:,None],P2[None])
Term3  = np.multiply(a3[:,None],P3[None])
Term4  = np.multiply(a4[:,None],P4[None])
LC = Term1 + Term2 + Term3 + Term4

Ax, Ay, Az = np.transpose(LC)

fig = ipv.figure()
# Plot the points
ipv.scatter(Ax,Ay,Az, size=2, color="#AD33FF", marker='sphere')
ipv.scatter(XVals,YVals,ZVals, size=3, marker='sphere')
# Add limits to axes
ipv.xyzlim(-3, 3)

# Plot axes surfaces
#plotAxesPlanes()

# Plot bounding box
#plotBoundingBox(XVals,YVals,ZVals)

ipv.show()

For **Conical Combination**, we have: $$ Each\,\, a_{i} \geq 0 $$

In [ ]:
# Get 1000 random Values for each of a1, a2, a3, and a4 between [0 to 1)
# Also satisfies the concical condiditon
a1, a2, a3, a4 = 1 * np.random.random_sample((4, 1000))

# Get A, B , C, D values from set array
P1, P2, P3, P4 = Points

# Multiply to get the Linear combination with the affine constraints
Term1  = np.multiply(a1[:,None],P1[None])
Term2  = np.multiply(a2[:,None],P2[None])
Term3  = np.multiply(a3[:,None],P3[None])
Term4  = np.multiply(a4[:,None],P4[None])
LC = Term1 + Term2 + Term3 + Term4

Ax, Ay, Az = np.transpose(LC)

fig = ipv.figure()
# Plot the points
ipv.scatter(Ax,Ay,Az, size=2, color="#AD33FF", marker='sphere') # Plot the Conical Linear Combination
ipv.scatter(XVals,YVals,ZVals, size=3, marker='sphere') # Plot the set S
# Add limits to axes
ipv.xyzlim(-3, 3)

# Plot axes surfaces
# plotAxesPlanes()

# Plot bounding box
plotBoundingBox(XVals,YVals,ZVals)

ipv.show()

And for the **Convex Combination** we have both the constraints:  
$$ \sum_{i=1}^{4} a_{i} = 1 \, and \, a_{i} \geq 0 $$

We will use
[Dirichlet Distribution](https://numpy.org/doc/stable/reference/random/generated/numpy.random.dirichlet.html "Optional Title")
 to generate random numbers. The Dirichlet distribution is a distribution over vectors x that fulfill the conditions: $$  \sum_{i=1}^k x_i = 1\, and \, x_i>0$$ [Wikipedia Page](https://en.wikipedia.org/wiki/Dirichlet_distribution "Optional Title")

In [ ]:
# Get 1000 random dirichlet Values for each of a1, a2, a3, and a4 between [0 to 1)
# Also satisfies the convex condiditon
# Dirichlet Distribution: 
a1, a2, a3, a4 = 1 * np.random.dirichlet(np.ones(4), 1000).transpose()

# Get A, B , C, D values from set array
P1, P2, P3, P4 = Points

# Multiply to get the Linear combination with the convex constraints
Term1  = np.multiply(a1[:,None],P1[None])
Term2  = np.multiply(a2[:,None],P2[None])
Term3  = np.multiply(a3[:,None],P3[None])
Term4  = np.multiply(a4[:,None],P4[None])
LC = Term1 + Term2 + Term3 + Term4

Ax, Ay, Az = np.transpose(LC)

fig = ipv.figure()
# Plot the points
ipv.scatter(Ax,Ay,Az, size=1, color="#AD33FF", marker='sphere') # Plot the Conical Linear Combination
ipv.scatter(XVals,YVals,ZVals, size=2, marker='sphere') # Plot the set S
# Add limits to axes
ipv.xyzlim(-3, 3)

# Plot axes surfaces
# plotAxesPlanes()

# Plot bounding box
plotBoundingBox(XVals,YVals,ZVals)

ipv.show()

In [ ]:
np.random.random_sample((4, 3))

In [ ]:
np.random.dirichlet(np.ones(4), 5)

In [ ]:
# Some helper functions (functions that help!!!)
def plotAxesPlanes():
    #Surfaces of XY, YZ, ZX planes
    YZVertices = np.array([[ 0.0, 3.0, 3.0],[ 0.0,-3.0, 3.0],[ 0.0, 3.0,-3.0],[ 0.0,-3.0,-3.0]])
    XZVertices = np.array([[ 3.0, 0.0, 3.0],[-3.0, 0.0, 3.0],[ 3.0, 0.0,-3.0],[-3.0, 0.0,-3.0]])
    XYVertices = np.array([[ 3.0, 3.0, 0.0],[ 3.0,-3.0, 0.0],[-3.0, 3.0, 0.0],[-3.0,-3.0, 0.0]])
    triangles = [(0,1,2),(1,2,3)]

    YZx, YZy, YZz = np.transpose(YZVertices)
    obj1 = ipv.plot_trisurf(YZx, YZy, YZz, triangles=triangles)
    obj1.color = [0., 0., 1., 0.5]
    obj1.material.transparent = True

    XZx, XZy, XZz = np.transpose(XZVertices)
    obj2 = ipv.plot_trisurf(XZx, XZy, XZz, triangles=triangles)
    obj2.color = [0., 1., 0., 0.5]
    obj2.material.transparent = True

    XYx, XYy, XYz = np.transpose(XYVertices)
    obj2 = ipv.plot_trisurf(XYx, XYy, XYz, triangles=triangles)
    obj2.color = [1., 0., 0., 0.5]
    obj2.material.transparent = True
    
    return None

def plotBoundingBox(XVals, YVals, ZVals):
    # Bounding box
    triangles = [(0, 1, 2),(1, 2, 3),(0, 1, 3),(0, 2, 3)]
    obj0 = ipv.plot_trisurf(XVals, YVals, ZVals, triangles=triangles)
    obj0.color = [0., 1., 1., 0.7]
    obj0.material.transparent = True    
    return None

<span style="font-family:Comic Sans MS">->>> Examples in HW3_4+ -->>></span> [Link for HW3 Questions4+ (Examples)](https://mybinder.org/v2/gh/Sridhar701Pitt/OptimizationPresentationMATH/master?filepath=HW3_4%2B_Updated.ipynb)

##### Visualizing Fundamental Theorem of Linear Programming in 3D

Let's take the same 4 points to be the vertices of the convex region:

P1 = ( 1.0, 1.0, 1.0)  
P2 = ( 2.0,-1.0, 0.0)  
P3 = (-2.0,-1.5, 0.5)  
P4 = (-1.0, 0.0,-0.5)

Consider the function F(p) = 2*X + 5*Y - 3*Z : we wish to maximize

Lets put that into a plot

In [ ]:
import numpy as np
import ipyvolume as ipv
import bqplot.scales

# Get 1000 random dirichlet Values for each of a1, a2, a3, and a4 between [0 to 1)
# Also satisfies the convex condiditon
# Dirichlet Distribution: 
a1, a2, a3, a4 = 1 * np.random.dirichlet(np.ones(4), 10000).transpose()

# Get A, B , C, D values from set array
P1, P2, P3, P4 = Points

# Multiply to get the Linear combination with the convex constraints
Term1  = np.multiply(a1[:,None],P1[None])
Term2  = np.multiply(a2[:,None],P2[None])
Term3  = np.multiply(a3[:,None],P3[None])
Term4  = np.multiply(a4[:,None],P4[None])
LC = Term1 + Term2 + Term3 + Term4

Ax, Ay, Az = np.transpose(LC)
# Compute the function
F = 2*Ax + 5*Ay - 3*Az

fig = ipv.figure()
# Plot the points

color_scale = bqplot.scales.ColorScale(min=min(F), max=max(F), colors=["#ff3", "#0f0", "#00f"])

ipv.scatter(Ax,Ay,Az, size=1,color = F, color_scale=color_scale, marker = 'sphere')

ipv.scatter(XVals,YVals,ZVals, size=2, marker='sphere') # Plot the set S

# Add limits to axes
ipv.xyzlim(-3, 3)

# Plot axes surfaces
# plotAxesPlanes()

# Plot bounding box
#plotBoundingBox(XVals,YVals,ZVals)

ipv.show()

<span style="font-family:Comic Sans MS">->>> Part 2 -->>>  </span>
[Link for Part 2](https://mybinder.org/v2/gh/Sridhar701Pitt/OptimizationPresentationMATH/master?filepath=Presentation%20-%20Optimization%20with%20Python%20P2.ipynb)